apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
{% for res in kustomization.resources %}
- {{ res.filename }}
{% endfor %}
namespace: {{ app.namespace }}

patches: []

configMapGenerator:
- name: {{ app.name }}-vars
  options:
    labels:
      config-map: {{ app.name }}-vars
  literals: []
